name: Get Domains

on:
  push:
    branches:
      - main

jobs:
  get_domains:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dig
      run: sudo apt-get install dnsutils -y

    - name: Get Domain Names
      run: |
        nslookup -type=ns vn. | grep "nameserver" | awk '{print $3}' > dns_servers.txt
        while read -r dns; do
          nslookup -type=ptr -timeout=5 "$dns" | grep "arpa" >> domains.txt
        done < dns_servers.txt
        cat domains.txt

    - name: Save Domains to File
      run: |
        mkdir -p artifacts
        mv domains.txt artifacts/
